-- +goose Up
-- Seed initial admin user
-- Email: ika.giorgadze@gmail.com
-- Password: BGP6969Geocell2015!
-- NOTE: password is stored as a bcrypt hash generated by the Go backend

INSERT INTO users (email, name, role, password_h, active)
VALUES (
           'ika.giorgadze@gmail.com',
           'Irakli Giorgadze',
           'admin',
           '$2a$12$epKmcro/6pW8TKGnb3svwOF9rpXUVbBYXePv/6kPtHEGw2dRvlG2.',
           TRUE
       )
ON CONFLICT (email) DO UPDATE
SET name      = EXCLUDED.name,
    role      = EXCLUDED.role,
    password_h = EXCLUDED.password_h,
    active    = EXCLUDED.active,
    updated_at = now();

-- +goose Down
DELETE FROM users WHERE email = 'ika.giorgadze@gmail.com';


